spring.application.name=kycloak-demo
server.port=1122

spring.datasource.url=jdbc:postgresql://localhost:5432/keycloak_demo
spring.datasource.username=postgres
spring.datasource.password=pg@@2018
spring.jpa.hibernate.ddl-auto=update


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/demo
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/demo/protocol/openid-connect/certs